import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {
  useEffect,
  useState
} from 'react'
// import Hls from "hls.js"
// "https://tailwindcss.com/img/card-top.jpg"
import useSWR from 'swr'
import { PlayIcon, PauseIcon } from '@heroicons/react/solid'
import Player from '../components/Player'
import Shows from '../components/Shows'



const Home = () => {

  const url = "http://s7.viastreaming.net:8310/;?_=0.494499115526442"
  const defaultImage = "https://spinitron.com/static/pictures/placeholders/loudspeaker.svg"

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://artxfm.org">Radio</a>
        </h1>

        <Player/>

        <Shows/>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

  // useEffect(() => {
  //   const audio = player;
  //   const hls = new Hls();
  //   // const url = 'https://ark3.spinitron.com/ark2/WXOX-20220220T190000Z/index.m3u8'
  //   const url = 'https://ark3.spinitron.com/ark2/WXOX-20220221T120000Z/index.m3u8'

  //   hls.loadSource(url);
  //   hls.attachMedia(audio);
  //   hls.on(Hls.Events.MANIFEST_PARSED, function() { audio.play(); });

  // }, [player]);
